### ISSUE TITLE
App execution error

### ISSUE THREAD

**Issue by Drift-Security** [june5079/soFrida#1]
Hi Team,

I am facing an issue when I am trying to run an app.py file. Find the error details below.

As per my observation If i tried to install adb or adb client package , it shows M2crypto build error.
```
(venv) Sxxxxxx-MacBook-Pro:soFrida sxxxxxxx$ pip install -r requirement.sf 
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already satisfied: selenium in ./venv/lib/python2.7/site-packages (from -r requirement.sf (line 1)) (3.141.0)
Requirement already satisfied: requests in ./venv/lib/python2.7/site-packages (from -r requirement.sf (line 2)) (2.22.0)
Requirement already satisfied: boto3 in ./venv/lib/python2.7/site-packages (from -r requirement.sf (line 3)) (1.10.28)
Requirement already satisfied: pure-python-adb in ./venv/lib/python2.7/site-packages (from -r requirement.sf (line 4)) (0.2.2.dev0)
Requirement already satisfied: termcolor in ./venv/lib/python2.7/site-packages (from -r requirement.sf (line 5)) (1.1.0)
Requirement already satisfied: flask in ./venv/lib/python2.7/site-packages (from -r requirement.sf (line 6)) (1.1.1)
Requirement already satisfied: frida in ./venv/lib/python2.7/site-packages (from -r requirement.sf (line 7)) (12.7.23)
Requirement already satisfied: flask_socketio in ./venv/lib/python2.7/site-packages (from -r requirement.sf (line 8)) (4.2.1)
Requirement already satisfied: awscli in ./venv/lib/python2.7/site-packages (from -r requirement.sf (line 9)) (1.16.292)
Requirement already satisfied: bs4 in ./venv/lib/python2.7/site-packages (from -r requirement.sf (line 10)) (0.0.1)
Requirement already satisfied: tqdm in ./venv/lib/python2.7/site-packages (from -r requirement.sf (line 11)) (4.39.0)
Requirement already satisfied: pathos in ./venv/lib/python2.7/site-packages (from -r requirement.sf (line 12)) (0.2.5)
Requirement already satisfied: google-api-python-client in ./venv/lib/python2.7/site-packages (from -r requirement.sf (line 13)) (1.7.11)
Requirement already satisfied: protobuf in ./venv/lib/python2.7/site-packages (from -r requirement.sf (line 14)) (3.11.0)
Requirement already satisfied: urllib3 in ./venv/lib/python2.7/site-packages (from selenium->-r requirement.sf (line 1)) (1.25.7)
Requirement already satisfied: certifi>=2017.4.17 in ./venv/lib/python2.7/site-packages (from requests->-r requirement.sf (line 2)) (2019.9.11)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./venv/lib/python2.7/site-packages (from requests->-r requirement.sf (line 2)) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in ./venv/lib/python2.7/site-packages (from requests->-r requirement.sf (line 2)) (2.8)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in ./venv/lib/python2.7/site-packages (from boto3->-r requirement.sf (line 3)) (0.9.4)
Requirement already satisfied: s3transfer<0.3.0,>=0.2.0 in ./venv/lib/python2.7/site-packages (from boto3->-r requirement.sf (line 3)) (0.2.1)
Requirement already satisfied: botocore<1.14.0,>=1.13.28 in ./venv/lib/python2.7/site-packages (from boto3->-r requirement.sf (line 3)) (1.13.28)
Requirement already satisfied: itsdangerous>=0.24 in ./venv/lib/python2.7/site-packages (from flask->-r requirement.sf (line 6)) (1.1.0)
Requirement already satisfied: Jinja2>=2.10.1 in ./venv/lib/python2.7/site-packages (from flask->-r requirement.sf (line 6)) (2.10.3)
Requirement already satisfied: click>=5.1 in ./venv/lib/python2.7/site-packages (from flask->-r requirement.sf (line 6)) (7.0)
Requirement already satisfied: Werkzeug>=0.15 in ./venv/lib/python2.7/site-packages (from flask->-r requirement.sf (line 6)) (0.16.0)
Requirement already satisfied: python-socketio>=4.3.0 in ./venv/lib/python2.7/site-packages (from flask_socketio->-r requirement.sf (line 8)) (4.4.0)
Requirement already satisfied: docutils<0.16,>=0.10 in ./venv/lib/python2.7/site-packages (from awscli->-r requirement.sf (line 9)) (0.15.2)
Requirement already satisfied: PyYAML<5.2,>=3.10; python_version != "2.6" and python_version != "3.3" in ./venv/lib/python2.7/site-packages (from awscli->-r requirement.sf (line 9)) (5.1.2)
Requirement already satisfied: rsa<=3.5.0,>=3.1.2 in ./venv/lib/python2.7/site-packages (from awscli->-r requirement.sf (line 9)) (3.4.2)
Requirement already satisfied: colorama<0.4.2,>=0.2.5; python_version != "2.6" and python_version != "3.3" in ./venv/lib/python2.7/site-packages (from awscli->-r requirement.sf (line 9)) (0.4.1)
Requirement already satisfied: beautifulsoup4 in /Library/Python/2.7/site-packages/beautifulsoup4-4.8.1-py2.7.egg (from bs4->-r requirement.sf (line 10)) (4.8.1)
Requirement already satisfied: ppft>=1.6.6.1 in ./venv/lib/python2.7/site-packages (from pathos->-r requirement.sf (line 12)) (1.6.6.1)
Requirement already satisfied: pox>=0.2.7 in ./venv/lib/python2.7/site-packages (from pathos->-r requirement.sf (line 12)) (0.2.7)
Requirement already satisfied: multiprocess>=0.70.9 in ./venv/lib/python2.7/site-packages (from pathos->-r requirement.sf (line 12)) (0.70.9)
Requirement already satisfied: dill>=0.3.1 in ./venv/lib/python2.7/site-packages (from pathos->-r requirement.sf (line 12)) (0.3.1.1)
Requirement already satisfied: httplib2<1dev,>=0.9.2 in ./venv/lib/python2.7/site-packages (from google-api-python-client->-r requirement.sf (line 13)) (0.14.0)
Requirement already satisfied: google-auth-httplib2>=0.0.3 in ./venv/lib/python2.7/site-packages (from google-api-python-client->-r requirement.sf (line 13)) (0.0.3)
Requirement already satisfied: uritemplate<4dev,>=3.0.0 in ./venv/lib/python2.7/site-packages (from google-api-python-client->-r requirement.sf (line 13)) (3.0.0)
Requirement already satisfied: six<2dev,>=1.6.1 in /Library/Python/2.7/site-packages/six-1.12.0-py2.7.egg (from google-api-python-client->-r requirement.sf (line 13)) (1.12.0)
Requirement already satisfied: google-auth>=1.4.1 in ./venv/lib/python2.7/site-packages (from google-api-python-client->-r requirement.sf (line 13)) (1.7.1)
Requirement already satisfied: setuptools in ./venv/lib/python2.7/site-packages (from protobuf->-r requirement.sf (line 14)) (42.0.1)
Requirement already satisfied: futures<4.0.0,>=2.2.0; python_version == "2.6" or python_version == "2.7" in /Library/Python/2.7/site-packages (from s3transfer<0.3.0,>=0.2.0->boto3->-r requirement.sf (line 3)) (3.3.0)
Requirement already satisfied: python-dateutil<2.8.1,>=2.1; python_version >= "2.7" in ./venv/lib/python2.7/site-packages (from botocore<1.14.0,>=1.13.28->boto3->-r requirement.sf (line 3)) (2.8.0)
Requirement already satisfied: MarkupSafe>=0.23 in ./venv/lib/python2.7/site-packages (from Jinja2>=2.10.1->flask->-r requirement.sf (line 6)) (1.1.1)
Requirement already satisfied: python-engineio>=3.9.0 in ./venv/lib/python2.7/site-packages (from python-socketio>=4.3.0->flask_socketio->-r requirement.sf (line 8)) (3.10.0)
Requirement already satisfied: pyasn1>=0.1.3 in ./venv/lib/python2.7/site-packages (from rsa<=3.5.0,>=3.1.2->awscli->-r requirement.sf (line 9)) (0.4.8)
Requirement already satisfied: soupsieve>=1.2 in ./venv/lib/python2.7/site-packages (from beautifulsoup4->bs4->-r requirement.sf (line 10)) (1.9.5)
Requirement already satisfied: cachetools<3.2,>=2.0.0 in ./venv/lib/python2.7/site-packages (from google-auth>=1.4.1->google-api-python-client->-r requirement.sf (line 13)) (3.1.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in ./venv/lib/python2.7/site-packages (from google-auth>=1.4.1->google-api-python-client->-r requirement.sf (line 13)) (0.2.7)
Requirement already satisfied: backports.functools-lru-cache; python_version < "3" in ./venv/lib/python2.7/site-packages (from soupsieve>=1.2->beautifulsoup4->bs4->-r requirement.sf (line 10)) (1.6.1)
(venv) Sxxxxx-MacBook-Pro:soFrida sxxxxxx$ python3 app.py
Traceback (most recent call last):
  File "app.py", line 20, in <module>
    from getinstalledapps import getInstalledApps
  File "/Volumes/Sxxxxxx/sof/soFrida/getinstalledapps.py", line 2, in <module>
    from adb.client import Client as AdbClient
ModuleNotFoundError: No module named 'adb.client'
```

**Comment by ssoyounk** [comment]
Hi~
Try to 
`python3 -m pip install  -r requirement.sf`
and retry
`python3 app.py`
your "pip" is seem to be  in python2.7.
